### ISSUE TITLE
2024년 9월 업데이트

### ISSUE THREAD

**Issue by MeganMagic** [MeganMagic/portfolio#11]
# Todo
- [ ] not-found 페이지 만들기
- [ ] project 섹션 내용 다듬기
- [ ] reference 섹션 추가하기
- [x] 외국어 성적 추가
- [x] education 섹션 수정
- [ ] header의 isActive 로직 고치기
- [ ] 블로그 섹션의 더 보기 버튼과 프로젝트 섹션의 더 보기 버튼 디자인 통일, or 공용 컴포넌트화
- [ ] 모바일 헤더 > 섹션 선택 시 메뉴 닫기 동작 추가
