### ISSUE TITLE
2024년 8월 업데이트

### ISSUE THREAD

**Issue by MeganMagic** [MeganMagic/portfolio#5]
# Todo
- [ ] OG 이미지 추가
- [ ] 검색엔진 최적화 작업
- [ ] 모바일(~640px) 헤더 만들기
- [ ] 경력 섹션 - 데이터 순서 정렬
- [ ] 자기소개 섹션 - 구성 변경, 내용 간소화
